### ISSUE TITLE
Can't import extension to MakeCode

### ISSUE THREAD

**Issue by miggalvez** [sphero-inc/sphero-sdk-microbit-makecode#2]
I've tried to add the SDK micro:bit extension to MakeCode, but when I enter the URL in the extension search box, I get: "We couldn't find any extensions matching 'https://github.com/sphero-inc/sphero-sdk-microbit-makecode.git'"

**Comment by abchatra** [comment]
This is because the pxt.json has reference LICENSE.md which doesn't exist in the repo. Please make sure all the files listed in pxt.json exists and relevant. 
License file need not exist in pxt.json file.

**Comment by microbit-mark** [comment]
@meganrobinson22 ^

**Comment by meganrobinson22** [comment]
Thanks everyone for bringing this to our attention! That should be fixed now, let me know if you still have any trouble.

**Comment by miggalvez** [comment]
I'm still getting the same error.

<img width="1073" alt="Screen Shot 2019-11-13 at 4 19 04 PM" src="https://user-images.githubusercontent.com/45237553/68809331-57894700-0631-11ea-914f-35c13cb3e88f.png">

**Comment by meganrobinson22** [comment]
Correct me if I'm wrong, but I believe that page will only show you extensions that are already published. Ours is currently in the process of being reviewed for publication, but you should still be able to import the extension by clicking the **Import** button on the **Home** screen.
![Screen Shot 2019-11-13 at 4 04 45 PM](https://user-images.githubusercontent.com/55854311/68812438-43911580-0630-11ea-8b70-fe7bcdc738f5.png)
![Screen Shot 2019-11-13 at 4 04 56 PM](https://user-images.githubusercontent.com/55854311/68812343-03ca2e00-0630-11ea-918e-51ebbf63e2ef.png)
![Screen Shot 2019-11-13 at 4 05 13 PM](https://user-images.githubusercontent.com/55854311/68812350-075db500-0630-11ea-8c6b-aa660833c4c2.png)
After that, make a new project and go to the **Extensions** page. Now you should be able to see the SpheroRVR repo, and you just need to click on it to add it to your project!
![Screen Shot 2019-11-13 at 4 12 59 PM](https://user-images.githubusercontent.com/55854311/68812610-bdc19a00-0630-11ea-8542-d64befc1e067.png)
Hope this helps! If that still isn't working for you please let me know and we will figure it out!

**Comment by abchatra** [comment]
There is another error: "failed to fetch tests.ts; 404"
I believe it should be test.ts

Please make sure all the listed files are correct

**Comment by abchatra** [comment]
Import is not working.

**Comment by meganrobinson22** [comment]
@abchatra sorry about that, that should be fixed now!
When you say the import is not working, do you mean from the Extensions page or from the Home page?

**Comment by miggalvez** [comment]
@meganrobinson22 Thanks. That workaround worked for me.
